[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
position = "before"
times = 1
pattern = "function Controller:key_hold_update(key, dt)"
payload = '''
local key_press_update_impl = Controller.key_press_update
local is_mac = love.system.getOS() == 'OS X'
local debug_leader_right = is_mac and 'rgui' or 'rctrl'
local debug_leader_left = is_mac and 'lgui' or 'lctrl'
function Controller:key_press_update(key, dt)
  if not _RELEASE_MODE then
    if
      self.held_keys[debug_leader_right]
      or self.held_keys[debug_leader_left]
    then
      return key_press_update_impl(self, key, dt)
    else
      require("typist")(self, key, dt)
    end
  else
    require("typist")(self, key, dt)
    return key_press_update_impl(self, key, dt)
  end
end
'''
match_indent = false

[[patches]]
[patches.pattern]
target = "globals.lua"
position = "after"
times = 1
pattern = "function Game:set_globals()"
payload = "    self.ORPHANED_UIBOXES = {}"
match_indent = false

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
position = "after"
times = 1
pattern = '''
        args.config.major = args.config.major or args.config.parent or self
'''
payload = '''
        if not args.config.parent then G.ORPHANED_UIBOXES[self] = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
position = "after"
pattern = "function UIBox:remove()"
times = 1
payload = "    G.ORPHANED_UIBOXES[self] = nil"
match_indent = false

[[patches]]
[patches.module]
source = "lib/cardarea-ext.lua"
before = "main.lua"
name = "typist.lib.cardarea-ext"

[[patches]]
[patches.module]
source = "lib/tblutils.lua"
before = "main.lua"
name = "typist.lib.tblutils"

[[patches]]
[patches.module]
source = "mod/init.lua"
before = "main.lua"
name = "typist"

[[patches]]
[patches.module]
source = "mod/cardarea-handler.lua"
before = "main.lua"
name = "typist.mod.cardarea-handler"

[[patches]]
[patches.module]
source = "mod/hand.lua"
before = "main.lua"
name = "typist.mod.hand"

[[patches]]
[patches.module]
source = "mod/handutils.lua"
before = "main.lua"
name = "typist.mod.handutils"

[[patches]]
[patches.module]
source = "mod/layout.lua"
before = "main.lua"
name = "typist.mod.layout"

[[patches]]
[patches.module]
source = "mod/state-handlers.lua"
before = "main.lua"
name = "typist.mod.state-handlers"
