[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
position = "before"
times = 1
pattern = "function Controller:key_hold_update(key, dt)"
payload = '''
local key_press_update_impl = Controller.key_press_update
function Controller:key_press_update(key, dt)
  if G.DEBUG then
    if self.held_keys["lctrl"] then
      require("typist")(self, key, dt)
    else
      return key_press_update_impl(self, key, dt)
    end
  else
    require("typist")(self, key, dt)
    return key_press_update_impl(self, key, dt)
  end
end
'''
match_indent = false

[[patches]]
[patches.pattern]
target = "globals.lua"
position = "after"
times = 1
pattern = "function Game:set_globals()"
payload = "    self.ORPHANED_UIBOXES = {}"
match_indent = false

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
position = "after"
times = 1
pattern = '''
        args.config.major = args.config.major or args.config.parent or self
'''
payload = '''
        if not args.config.parent then G.ORPHANED_UIBOXES[self] = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
position = "after"
pattern = "function UIBox:remove()"
times = 1
payload = "    G.ORPHANED_UIBOXES[self] = nil"
match_indent = false

[[patches]]
[patches.module]
source = "lib/cardarea-ext.lua"
before = "main.lua"
name = "typist.lib.cardarea-ext"

[[patches]]
[patches.module]
source = "lib/tblutils.lua"
before = "main.lua"
name = "typist.lib.tblutils"

[[patches]]
[patches.module]
source = "init.lua"
before = "main.lua"
name = "typist"

[[patches]]
[patches.module]
source = "cardarea-handler.lua"
before = "main.lua"
name = "typist.cardarea-handler"

[[patches]]
[patches.module]
source = "hand.lua"
before = "main.lua"
name = "typist.hand"

[[patches]]
[patches.module]
source = "handutils.lua"
before = "main.lua"
name = "typist.handutils"

[[patches]]
[patches.module]
source = "layout.lua"
before = "main.lua"
name = "typist.layout"

[[patches]]
[patches.module]
source = "state-handlers.lua"
before = "main.lua"
name = "typist.state-handlers"
